markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Kamil Madac
production_url : http://kmadac.github.io
description: "Codes, projects, thoughts and other things by Kamil Madac."
author :
  name : Kamil Madac
  github : kmadac
  twitter : kmadac
  email: kamil.madac@gmail.com
